### ISSUE TITLE
SmoothGradCAMpp produces a tensor of NAN

### ISSUE THREAD

**Issue by lustea0201** [yiskw713/SmoothGradCAMplusplus#1]
Depending on the input and the chosen method, I sometimes get NaN as an output. Why could this be and how can I fix it ?

![image](https://user-images.githubusercontent.com/37267928/75788598-79b8e900-5d36-11ea-8f0d-02abd9c90db8.png)

**Comment by yiskw713** [comment]
Hi lustea0201,

Thank you for visiting my repository and sorry for the delay in replying.
If possible, could you share the input image with me? Then, I'll investigate why Smooth Grad-CAM++ does not work.

Best regard,

**Comment by lustea0201** [comment]
Here is an example: 
![image](https://user-images.githubusercontent.com/37267928/77527334-3ad90780-6e8c-11ea-972b-3d08744e9256.png)


Which result from using: 
![im0_147](https://user-images.githubusercontent.com/37267928/77527700-f00bbf80-6e8c-11ea-8efe-2e32da90b6ef.png)

Thank you for your help !
